/**
 * Shared helpers for the Field Inspector serverless functions (Vercel).
 * Library data: api/defect-lib.json — compact copy of the BCNSW iAuditor
 * Master Defect Library, regenerated by the dbp-site-inspector skill scripts.
 */
import Anthropic from "@anthropic-ai/sdk";
import lib from "./defect-lib.json";

export interface CompactEntry {
  id: string;
  rg: string;   // regime
  sub: string;  // subcategory
  d: string;    // description
  c19: string;  // NCC 2019 refs (compact)
  c22: string;  // NCC 2022 refs (compact)
  pw: string;   // RAB pathway s33(2) | s34(1)(a) | ""
  st: string;   // active | draft | catchall
  sw?: string;  // scope of work preview (omitted in the cloud build to keep the bundle small)
}

export const LIBRARY = lib as unknown as Record<string, CompactEntry>;

export const SCAN_MODEL = "claude-haiku-4-5-20251001";
export const IDENTIFY_MODEL = "claude-sonnet-5";

const INDEX_TEXT = Object.values(LIBRARY)
  .filter(e => e.st === "active")
  .map(e => `${e.id}|${e.rg}|${e.sub || "-"}|${e.d.replace(/\s+/g, " ").slice(0, 110)}`)
  .join("\n");

export const SCAN_SYSTEM = `You are an expert NSW construction defect spotter (DBP Act 2020 / RAB Act 2020, NCC) looking at ONE frame from a live phone camera during a site inspection.

Decide whether any defect from the INDEX below is CLEARLY visible in this frame.
PRECISION OVER RECALL: flag only what you can genuinely see. A typical walkthrough frame contains NO flaggable defect. Never flag from blur, shadows or guesswork.

Reply with ONLY this JSON (no markdown):
{"detections":[{"id":"W1.3","label":"short plain-language label","cx":0.52,"cy":0.61,"r":0.12,"confidence":"high|medium"}]}
- detections MUST be [] when nothing is clearly visible.
- cx, cy, r = centre and radius of the defect area, relative (0-1) to this frame.
- id MUST come from the INDEX. Max 2 detections.

INDEX (id|regime|subcategory|defect):
${INDEX_TEXT}`;

export const IDENTIFY_SYSTEM = `You are an expert NSW site inspector (DBP Act 2020 / RAB Act 2020, NCC, Australian Standards) classifying a photo DELIBERATELY taken of a suspected defect during a Class 2/3/9c inspection.

Match the photo against the INDEX below. Reply with ONLY this JSON (no markdown):
{"observation":"1-2 sentences: element, material, what is visibly wrong","findings":[{"id":"W1.3","cx":0.5,"cy":0.6,"r":0.12,"confidence":"high|medium|low","note":"why this id fits"}]}
Rules:
- id MUST come from the INDEX. Max 3 findings, best first.
- confidence high = the library condition is unambiguously visible; medium = consistent but a measurement/second angle would confirm; low = plausible only.
- If something is clearly defective but no INDEX item fits, use the regime catch-all id: Waterproofing W3.1, Fire Safety F9.1, Structure S5.1, Building Enclosure BE5.1_alt, Essential Services ES7.1.
- If nothing is defective, findings = [].

INDEX (id|regime|subcategory|defect):
${INDEX_TEXT}`;

export function parseModelJson(text: string): any | null {
  let s = text.trim();
  const fenced = s.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) s = fenced[1].trim();
  const start = s.indexOf("{");
  const end = s.lastIndexOf("}");
  if (start === -1 || end <= start) return null;
  try {
    return JSON.parse(s.slice(start, end + 1));
  } catch {
    return null;
  }
}

export const clamp01 = (n: unknown, fb: number) => {
  const v = Number(n);
  return Number.isFinite(v) ? Math.min(1, Math.max(0, v)) : fb;
};

export const stripDataUrl = (b64: string) => b64.replace(/^data:[^;]+;base64,/, "");

export function anthropicOrNull(): Anthropic | null {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  return apiKey ? new Anthropic({ apiKey }) : null;
}

/** Optional shared-code gate (set FIELD_ACCESS_CODE env to enable). Returns true when the request was rejected. */
export function gate(req: any, res: any): boolean {
  const code = process.env.FIELD_ACCESS_CODE;
  if (code && req.headers["x-field-code"] !== code) {
    res.status(401).json({ error: "code_required" });
    return true;
  }
  return false;
}

export function readBody(req: any): any {
  // Vercel parses JSON bodies automatically when content-type is application/json
  return typeof req.body === "string" ? JSON.parse(req.body || "{}") : req.body || {};
}
