/**
 * Field Inspector API — live defect scanning from phone/tablet camera.
 *
 *   GET  /api/field/status    → { ai, items }
 *   POST /api/field/scan      → fast Haiku pass on a live camera frame → red-circle detections
 *   POST /api/field/identify  → Sonnet pass on the captured photo → enriched library findings
 *   POST /api/field/save      → stores original + marked photo, appends findings_register.csv
 *
 * Matching is restricted to the BCNSW iAuditor Master Defect Library bundled at
 * server/defect-library.json (regenerated by the dbp-site-inspector skill's
 * refresh_library.mjs whenever the master Excel changes).
 */
import { Router, Request, Response } from "express";
import Anthropic from "@anthropic-ai/sdk";
import fs from "fs";
import path from "path";
import defectLibraryJson from "../defect-library.json";

const router = Router();

const SCAN_MODEL = "claude-haiku-4-5-20251001";
const IDENTIFY_MODEL = "claude-sonnet-5";

interface DefectEntry {
  id: string;
  regime: string;
  subcategory: string | null;
  description: string | null;
  consequence: string | null;
  ncc2019: string | null;
  ncc2022: string | null;
  section_choice: string | null;
  scope_of_work: string | null;
  serious_reason: string | null;
  special_notes: string | null;
  status: "active" | "draft" | "catchall";
}

const LIBRARY = defectLibraryJson as unknown as Record<string, DefectEntry>;
const CATCHALLS: Record<string, string> = {
  Waterproofing: "W3.1",
  "Fire Safety": "F9.1",
  Structure: "S5.1",
  "Building Enclosure": "BE5.1_alt",
  "Essential Services": "ES7.1",
};

// Compact matching index — active items only (drafts excluded from live scanning).
const INDEX_TEXT = Object.values(LIBRARY)
  .filter(e => e.status === "active")
  .map(e => `${e.id}|${e.regime}|${e.subcategory || "-"}|${(e.description || "").replace(/\s+/g, " ").slice(0, 110)}`)
  .join("\n");

const SCAN_SYSTEM = `You are an expert NSW construction defect spotter (DBP Act 2020 / RAB Act 2020, NCC) looking at ONE frame from a live phone camera during a site inspection.

Decide whether any defect from the INDEX below is CLEARLY visible in this frame.
PRECISION OVER RECALL: flag only what you can genuinely see. A typical walkthrough frame contains NO flaggable defect. Never flag from blur, shadows or guesswork.

Reply with ONLY this JSON (no markdown):
{"detections":[{"id":"W1.3","label":"short plain-language label","cx":0.52,"cy":0.61,"r":0.12,"confidence":"high|medium"}]}
- detections MUST be [] when nothing is clearly visible.
- cx, cy, r = centre and radius of the defect area, relative (0-1) to this frame.
- id MUST come from the INDEX. Max 2 detections.

INDEX (id|regime|subcategory|defect):
${INDEX_TEXT}`;

const IDENTIFY_SYSTEM = `You are an expert NSW site inspector (DBP Act 2020 / RAB Act 2020, NCC, Australian Standards) classifying a photo DELIBERATELY taken of a suspected defect during a Class 2/3/9c inspection.

Match the photo against the INDEX below. Reply with ONLY this JSON (no markdown):
{"observation":"1-2 sentences: element, material, what is visibly wrong","findings":[{"id":"W1.3","cx":0.5,"cy":0.6,"r":0.12,"confidence":"high|medium|low","note":"why this id fits"}]}
Rules:
- id MUST come from the INDEX. Max 3 findings, best first.
- confidence high = the library condition is unambiguously visible; medium = consistent but a measurement/second angle would confirm; low = plausible only.
- If something is clearly defective but no INDEX item fits, use the regime catch-all id: Waterproofing W3.1, Fire Safety F9.1, Structure S5.1, Building Enclosure BE5.1_alt, Essential Services ES7.1.
- If nothing is defective, findings = [].

INDEX (id|regime|subcategory|defect):
${INDEX_TEXT}`;

/** Tolerant JSON extraction from a model reply. */
function parseModelJson(text: string): any | null {
  let s = text.trim();
  const fenced = s.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenced) s = fenced[1].trim();
  const start = s.indexOf("{");
  const end = s.lastIndexOf("}");
  if (start === -1 || end <= start) return null;
  try {
    return JSON.parse(s.slice(start, end + 1));
  } catch {
    return null;
  }
}

/** Extract compact clause tokens (F1P2, F1D5, FP1.4, AS 4654.2-2012…) from library text. */
function extractRefs(text: string | null): string {
  if (!text) return "";
  const patterns = [
    /\b[A-Z]{1,2}\d{1,2}[PD]\d{1,2}\b/g, // NCC 2022 style: F1P2, F1D5, C3D13
    /\b[A-Z]{1,2}P?\d{1,2}\.\d{1,2}\b/g, // NCC 2019 style: FP1.4, F1.4, D2.13
    /\bAS(?:\/NZS)?\s?\d{3,5}(?:\.\d{1,2})?(?:[-:]\d{4})?\b/g,
    /\bSpec(?:ification)?\s\d{1,3}\b/gi,
  ];
  const found: string[] = [];
  for (const re of patterns) {
    for (const m of text.match(re) || []) {
      const token = m.replace(/\s+/g, " ").trim();
      if (!found.includes(token)) found.push(token);
    }
  }
  return found.slice(0, 8).join(" · ");
}

function pathwayOf(entry: DefectEntry): string {
  const c = entry.section_choice || "";
  if (c.includes("s33(2)")) return "s33(2)";
  if (c.includes("s34(1)(a)")) return "s34(1)(a)";
  return "";
}

function clamp01(n: unknown, fallback: number): number {
  const v = Number(n);
  return Number.isFinite(v) ? Math.min(1, Math.max(0, v)) : fallback;
}

function stripDataUrl(b64: string): string {
  return b64.replace(/^data:[^;]+;base64,/, "");
}

function enrich(id: string) {
  const e = LIBRARY[id];
  if (!e) return null;
  return {
    id: e.id,
    regime: e.regime,
    subcategory: e.subcategory,
    description: e.description,
    status: e.status,
    ncc2022Refs: extractRefs(e.ncc2022),
    ncc2019Refs: extractRefs(e.ncc2019),
    pathway: pathwayOf(e),
    scopeOfWork: e.scope_of_work,
    seriousReason: e.serious_reason,
    specialNotes: e.special_notes,
  };
}

function anthropicOrNull(): Anthropic | null {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  return apiKey ? new Anthropic({ apiKey }) : null;
}

const NO_KEY = {
  error: "ANTHROPIC_API_KEY not configured",
  message: "Set ANTHROPIC_API_KEY to enable AI scanning. Demo mode is available in the page.",
};

router.get("/status", (_req: Request, res: Response) => {
  res.json({
    ai: !!process.env.ANTHROPIC_API_KEY,
    items: Object.keys(LIBRARY).length,
    active: Object.values(LIBRARY).filter(e => e.status === "active").length,
  });
});

/** Fast pass on a downscaled live frame. Body: { image: base64 jpeg } */
router.post("/scan", async (req: Request, res: Response) => {
  const client = anthropicOrNull();
  if (!client) return res.status(503).json(NO_KEY);
  const image = stripDataUrl(String(req.body?.image || ""));
  if (!image) return res.status(400).json({ error: "image (base64 jpeg) required" });

  try {
    const message = await client.messages.create({
      model: SCAN_MODEL,
      max_tokens: 300,
      temperature: 0,
      system: [{ type: "text", text: SCAN_SYSTEM, cache_control: { type: "ephemeral" } }],
      messages: [
        {
          role: "user",
          content: [
            { type: "image", source: { type: "base64", media_type: "image/jpeg", data: image } },
            { type: "text", text: "Scan this frame. JSON only." },
          ],
        },
      ],
    });
    const text = message.content
      .filter((b): b is Anthropic.Messages.TextBlock => b.type === "text")
      .map(b => b.text)
      .join("");
    const parsed = parseModelJson(text);
    const detections = (Array.isArray(parsed?.detections) ? parsed.detections : [])
      .filter((d: any) => d && typeof d.id === "string" && LIBRARY[d.id])
      .slice(0, 2)
      .map((d: any) => ({
        id: d.id,
        label: String(d.label || LIBRARY[d.id].description || d.id).slice(0, 80),
        regime: LIBRARY[d.id].regime,
        cx: clamp01(d.cx, 0.5),
        cy: clamp01(d.cy, 0.5),
        r: Math.min(0.45, Math.max(0.04, clamp01(d.r, 0.12))),
        confidence: d.confidence === "high" ? "high" : "medium",
      }));
    return res.json({ detections });
  } catch (err: any) {
    console.error("field/scan error:", err.message);
    return res.status(502).json({ error: "scan failed", message: err.message });
  }
});

/** Full pass on the captured photo. Body: { image: base64 jpeg, hintIds?: string[] } */
router.post("/identify", async (req: Request, res: Response) => {
  const client = anthropicOrNull();
  if (!client) return res.status(503).json(NO_KEY);
  const image = stripDataUrl(String(req.body?.image || ""));
  if (!image) return res.status(400).json({ error: "image (base64 jpeg) required" });
  const hintIds = (Array.isArray(req.body?.hintIds) ? req.body.hintIds : [])
    .filter((id: unknown): id is string => typeof id === "string" && !!LIBRARY[id])
    .slice(0, 3);

  try {
    const message = await client.messages.create({
      model: IDENTIFY_MODEL,
      max_tokens: 1200,
      temperature: 0,
      system: [{ type: "text", text: IDENTIFY_SYSTEM, cache_control: { type: "ephemeral" } }],
      messages: [
        {
          role: "user",
          content: [
            { type: "image", source: { type: "base64", media_type: "image/jpeg", data: image } },
            {
              type: "text",
              text: hintIds.length
                ? `Photo taken by the inspector. Live scan suggested: ${hintIds.join(", ")} — verify, do not blindly accept. JSON only.`
                : "Photo taken by the inspector. JSON only.",
            },
          ],
        },
      ],
    });
    const text = message.content
      .filter((b): b is Anthropic.Messages.TextBlock => b.type === "text")
      .map(b => b.text)
      .join("");
    const parsed = parseModelJson(text);
    const findings = (Array.isArray(parsed?.findings) ? parsed.findings : [])
      .filter((f: any) => f && typeof f.id === "string" && LIBRARY[f.id])
      .slice(0, 3)
      .map((f: any) => ({
        ...enrich(f.id),
        cx: clamp01(f.cx, 0.5),
        cy: clamp01(f.cy, 0.5),
        r: Math.min(0.45, Math.max(0.04, clamp01(f.r, 0.15))),
        confidence: ["high", "medium", "low"].includes(f.confidence) ? f.confidence : "low",
        note: String(f.note || "").slice(0, 300),
      }));
    return res.json({ observation: String(parsed?.observation || "").slice(0, 400), findings });
  } catch (err: any) {
    console.error("field/identify error:", err.message);
    return res.status(502).json({ error: "identify failed", message: err.message });
  }
});

/**
 * Persist a confirmed finding.
 * Body: { project, location, verdict, confidence, notes, defectId,
 *         imageBase64, markedBase64 }
 * Files land in FIELD_INSPECTIONS_DIR (default <cwd>/inspections) under
 * <YYYY-MM-DD>_<project>/ with a findings_register.csv matching the
 * dbp-site-inspector skill's register schema.
 */
router.post("/save", (req: Request, res: Response) => {
  try {
    const { project, location, verdict, confidence, notes, defectId, imageBase64, markedBase64 } = req.body || {};
    const entry: DefectEntry | undefined = LIBRARY[String(defectId)];
    if (!entry) return res.status(400).json({ error: "unknown defectId" });
    const img = Buffer.from(stripDataUrl(String(imageBase64 || "")), "base64");
    if (!img.length) return res.status(400).json({ error: "imageBase64 required" });
    if (img.length > 8 * 1024 * 1024) return res.status(413).json({ error: "image too large" });
    const marked = markedBase64 ? Buffer.from(stripDataUrl(String(markedBase64)), "base64") : null;

    const slug = (String(project || "Site").replace(/[^A-Za-z0-9-_ ]+/g, "").trim().replace(/\s+/g, "-") || "Site").slice(0, 40);
    const day = new Date().toISOString().slice(0, 10);
    const baseDir = process.env.FIELD_INSPECTIONS_DIR || path.join(process.cwd(), "inspections");
    const dir = path.join(baseDir, `${day}_${slug}`);
    fs.mkdirSync(dir, { recursive: true });

    const csvPath = path.join(dir, "findings_register.csv");
    const header = "seq,timestamp,project,location,defect_id,verdict,confidence,description_short,ncc2022_ref_short,pathway,photo_original,photo_marked,notes\n";
    if (!fs.existsSync(csvPath)) fs.writeFileSync(csvPath, header, "utf8");
    const seq = Math.max(1, fs.readFileSync(csvPath, "utf8").trim().split(/\r?\n/).length); // header + rows → next seq
    const nn = String(seq).padStart(2, "0");
    const safeId = entry.id.replace(/[^A-Za-z0-9._-]+/g, "-");

    const photoName = `${nn}_${safeId}.jpg`;
    fs.writeFileSync(path.join(dir, photoName), img);
    let markedName = "";
    if (marked?.length) {
      markedName = `${nn}_${safeId}_marked.jpg`;
      fs.writeFileSync(path.join(dir, markedName), marked);
    }

    const q = (v: unknown) => `"${String(v ?? "").replace(/"/g, '""').replace(/\r?\n/g, " ")}"`;
    const row = [
      seq,
      new Date().toISOString(),
      q(project || "Site"),
      q(location || ""),
      entry.id,
      q(verdict || "confirmed"),
      q(confidence || ""),
      q((entry.description || "").slice(0, 120)),
      q(extractRefs(entry.ncc2022)),
      pathwayOf(entry),
      photoName,
      markedName,
      q(notes || ""),
    ].join(",");
    fs.appendFileSync(csvPath, row + "\n", "utf8");

    return res.json({ ok: true, seq, folder: dir, files: [photoName, markedName].filter(Boolean) });
  } catch (err: any) {
    console.error("field/save error:", err.message);
    return res.status(500).json({ error: "save failed", message: err.message });
  }
});

export default router;
